# configuring action
name: Get & Cache Dependencies
description: Get dependencies via npm and cache them for further usage.
inputs:
  working_directory: 
    description: working_directory for execution
    default: ./
  debug-info: 
    description: debuging location and hashFiles
    default: 'false'
  caching:
    description: Whether to cache depencencies or not.
    default: 'true'
    required: false
outputs:
  used-cache:
    description: Whether the cache was used.
    value: '${{ steps.install }}'
runs:
  using: 'composite'
  steps:
    - name: Debug info
      shell: bash
      if: inputs.debug-info == 'true'
      working-directory: ${{ inputs.working_directory }}
      run: | 
        pwd
        ls -la
    - name: Cache dependecies
      uses: actions/cache@v3
      if: inputs.caching == 'true'
      id: cache
      with: # optimizations for faster execution (not global .npm just current node_modules)
        path: ${{inputs.working_directory}}/node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      working-directory: ${{ inputs.working_directory }}
      run: npm ci
    - name: Create output
      shell: bash
      id: install
      run: echo "cache='${{ inputs.caching }}' >> $GITHUB_OUTPUT"
    - name: Debug info
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      if: inputs.debug-info == 'true'
      run: ls -la
