# configuring action
name: Get & Cache Dependencies
description: Get dependencies via npm and cache them for further usage.
inputs:
  working_directory: 
    description: working_directory for execution
    default: ./
  debug-info: 
    description: debuging location and hashFiles
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Debug info
      shell: bash
      if: ${{ inputs.debug-info }} == 'true'
      run: | 
        pwd
        ls -la
    - name: Cache dependecies
      uses: actions/cache@v3
      id: cache
      with: # optimizations for faster execution (not global .npm just current node_modules)
        path: ${{inputs.working_directory}}/node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: Debug info
      shell: bash
      if: ${{ inputs.debug-info }} == 'true'
      run: ls -la
