name: Deployment (Container)
on:
  push:
    branches:
      - main
    paths:
      - "playwright/**"
      - ".github/workflows/deploy_docker.yml"
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: ${{ vars.MONGODB_DB_NAME }}
jobs:
  test:
    environment: Testing-docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: playwright
    container:
      image: node:16
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb+srv
      MONGODB_CLUSTER_ADDRESS: cluster0.tihhnqc.mongodb.net
      PORT: 8080
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
      - name: Install Dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run Tests
        run: npm test
      - name: Output info
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
