name: Deployment (Container)
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy_docker.yml"
  workflow_dispatch:
env:
  working_directory: playwright
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: ${{ vars.MONGODB_DB_NAME }}
jobs:
  test:
    environment: Testing-docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working_directory}}
    # Without container section is still possible to use services containers but then need to use HOST address 127.0.0.1 and port 27017 for mongo
    container:
      image: node:16
    services: # images from docker (refering to documentaion of each "service" image) work if job is goging in container
      mongodb-service:
        image: mongo
        ports: # needs if running without container section
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{env.MONGODB_USERNAME}}
          MONGO_INITDB_ROOT_PASSWORD: ${{env.MONGODB_PASSWORD}}
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_CLUSTER_ADDRESS: mongodb-service
      MONGODB_CLUSTER_ADDRESS_WITHOUT_CONTAINER_SECTION: 127.0.0.1
      PORT: 8080
      MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
      MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
      test_resilts_artifact: report
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
          path: ${{env.working_directory}}/node_modules
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run Tests
        run: npm test
      - name: Output info
        run: |
          pwd
          ls -la
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
      - name: Upload Test results
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.test_resilts_artifact}}
          path: |
            ${{env.working_directory}}/playwright-report
            ${{env.working_directory}}/playwright.config.js
          retention-days: 1
          if-no-files-found: warn
  deploy:
    needs: test
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
