name: Deploy with Custom actions
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - ".github/workflows/deploy_with_custom_action.yml"
env: # workflow env variables
  working_directory: react_new
  test-artifact: test-results-report
  artifact-name: build
defaults:
  run:
    working-directory: react_new
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        id: run-tests
        with:
          working_directory: ${{env.working_directory}}
          debug-info: true
      - name: Output Information
        run: echo "Check state=${{ toJson(steps.run-tests.outputs) }}"
      - name: Test code
        run: npm run test
      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        if: failure() && steps.run-tests.outcome == 'failure'
        with:
          name: ${{env.test-artifact}}
          path: ${{env.working_directory}}/test.json

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        with:
          working_directory: ${{env.working_directory}}
      - name: Lint Code
        run: npm run lint

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        with:
          working_directory: ${{env.working_directory}}
      - name: Build code
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact-name }}
          path: |
            ${{env.working_directory}}/package.json
            ${{env.working_directory}}/dist
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifact-name }}
      - name: Output content
        run: |
          ls -la
          pwd
      - name: Deploy Placeholder
        run: echo "Deploying build..."

  report:
    needs: test
    runs-on: ubuntu-latest
    if: failure() || cancelled()
    defaults:
      run:
        working-directory: .
    steps:
      - name: Output github info
        run: |
          echo "Something went wrong"
          echo "${{ toJson(github) }}"
      - name: Upload report
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.test-artifact }}
      - name: Output content
        run: |
          ls -la
          pwd
      - name: Output report info
        run: cat test.json

  information:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
      - name: Run custom action
        uses: ./.github/actions/deploy-s3-javascript
