name: Deployment (Container)
on:
  push:
    branches:
      - main
    paths:
      - "playwright/**"
      - ".github/workflows/deploy_docker.yml"
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: ${{ vars.MONGODB_DB_NAME }}
jobs:
  test:
    environment: Testing-docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: playwright
    container:
      image: node:16
    services: # images from docker (refering to documentaion of each "service" image) work if job is goging in container
      mongodb-service:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{env.MONGODB_USERNAME}}
          MONGO_INITDB_ROOT_PASSWORD: ${{env.MONGODB_PASSWORD}}
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_CLUSTER_ADDRESS: mongodb-service
      PORT: 8080
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
      - name: Install Dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run Tests
        run: npm test
      - name: Output info
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
