name: Events Demo
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - review_requested
      - ready_for_review
    branches:
      - main
    paths-ignore:
      - playwright
      - ".github/workflows/*"
      - react_new
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/**
    paths-ignore:
      - ".github/workflows/*"
      - playwright
      - react_new
jobs:
  lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./react
    steps:
      - name: "First: download the code for ubuntu server"
        uses: actions/checkout@v3
      - name: Check pwd
        run: pwd
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-20.04
    env:
      working-directory: ./react
    steps:
      - name: "First: download the code for ubuntu server"
        uses: actions/checkout@v3
      - name: Check pwd
        run: pwd
      - name: "Install nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: |
          pwd
          npm ci
      - name: Run tests after install
        working-directory: ${{env.working-directory}}
        run: |
          pwd
          npm test
  build:
    needs: [test, lint]
    runs-on: ubuntu-20.04
    outputs: # publishing output
      script-file: ${{steps.publish-file.outputs.script-file}} # need an id!
    env:
      working-directory: ./react
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - name: "First: download the code for ubuntu server"
        uses: actions/checkout@v3
      - name: "Install nodejs"
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Get publishet JS file from build
        id: publish-file
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';' # need also publish output...!
      - name: check working directory
        run: |
          pwd 
          ls -la
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-build-files
          path: |
            ${{env.working-directory}}/dist
            ${{env.working-directory}}/package.json
          if-no-files-found: error #warn/ignore/error
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        id: download
        with:
          name: dist-build-files
      - name: check working directory
        run: |
          pwd 
          ls -la
          ls -la dist
          echo ${{steps.download.outputs.download-path}}
      - name: Output generated filename from previous build
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "deploying placeholder..."
