name: Events Demo
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - review_requested
      - ready_for_review
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./react
    steps:
      - name: "First: download the code for ubuntu server"
        uses: actions/checkout@v3
      - name: Check pwd
        run: pwd
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-20.04
    env:
      working-directory: ./react
    steps:
      - name: "First: download the code for ubuntu server"
        uses: actions/checkout@v3
      - name: Check pwd
        run: pwd
      - name: "Install nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: |
          pwd
          npm ci
      - name: Run tests after install
        working-directory: ${{env.working-directory}}
        run: |
          pwd
          npm test
