name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "First: download the code for ubuntu server"
        uses: actions/checkout@v3
      - name: "Install nodejs and dependencies"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests after install
        run: npm test
