name: Test Project and Deploy
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./react
    steps:
      - name: "First: download the code for ubuntu server"
        uses: actions/checkout@v3
      - name: Check pwd
        run: pwd
      - name: "Install nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: |
          pwd
          npm ci
      - name: Run tests after install
        working-directory: ${{env.working-directory}}
        run: |
          pwd
          npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      working-directory: ./react
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pwd
          npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."
