name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./react
    steps:
      - name: "First: download the code for ubuntu server"
        uses: actions/checkout@v3
      - name: Check pwd
        run: pwd
      - name: "Install nodejs and dependencies"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: |
          pwd
          npm ci
      - name: Run tests after install
        working-directory: ${{env.working-directory}}
        run: |
          pwd
          npm test
